# Generated by Django 4.2.15 on 2026-09-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_fix_bodybuilding_category_keyword_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='هدف')),
                ('name_en', models.CharField(max_length=80, unique=True, verbose_name='نام انگلیسی هدف')),
            ],
            options={
                'verbose_name': 'هدف برنامه',
                'verbose_name_plural': 'اهداف برنامه',
                'ordering': ['name'],
            },
        ),
    ]
