# Generated by Django 4.2.15 on 2026-09-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_seed_exercise_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogramexercise',
            name='goal',
            field=models.CharField(blank=True, max_length=80, verbose_name='هدف حرکت'),
        ),
    ]
