# Generated by Django 4.2.15 on 2026-09-24 07:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_workoutprogramexercise_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('disease', 'بیماری'), ('abnormality', 'ناهنجاری'), ('injury', 'آسیب'), ('medication', 'دارو'), ('allergy', 'حساسیت')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سابقه سلامت کاربر',
                'verbose_name_plural': 'سوابق سلامت کاربران',
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['user', 'category'], name='account_use_user_id_57ec6b_idx'), models.Index(fields=['user', 'recorded_at'], name='account_use_user_id_46c180_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('anxiety_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='میزان اضطراب')),
                ('motivation_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='میزان انگیزه')),
                ('sleep_quality_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='کیفیت خواب')),
                ('training_satisfaction_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='رضایت از کیفیت تمرین')),
                ('resting_heart_rate_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='وضعیت ضربان قلب استراحت صبحگاهی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت روحیات روزانه',
                'verbose_name_plural': 'ثبت روحیات روزانه',
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['user', 'entry_date'], name='account_dai_user_id_0f7678_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailymoodentry',
            constraint=models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_user_mood_entry_date'),
        ),
    ]
