# Generated by Django 4.2.15 on 2026-09-24 08:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_userhealthrecord_dailymoodentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymoodentry',
            name='resting_heart_rate_score',
        ),
        migrations.CreateModel(
            name='DailyHeartRateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('bpm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)], verbose_name='ضربان قلب (ضربان در دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_entries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت ضربان قلب روزانه',
                'verbose_name_plural': 'ثبت ضربان قلب روزانه',
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['user', 'entry_date'], name='account_dai_user_id_e232f6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyheartrateentry',
            constraint=models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_user_heart_rate_entry_date'),
        ),
    ]
