# Generated by Django 4.2.15 on 2026-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_workout_best_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='admin_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده توسط ادمین'),
        ),
    ]
