# Generated by Django 4.2.15 on 2026-09-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_notificationdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='abdominal_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر شکم'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='axilla_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر زیربغل'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='biceps_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر جلوبازو'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='calf_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر پشت ساق پا'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='chest_armpit_men_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر سینه'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='chest_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر کمر'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='pushed_attachments_to_files',
            field=models.BooleanField(default=False, verbose_name='پیوست\u200cها به فایل\u200cهای کاربر افزوده شد'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='pushed_to_caliper',
            field=models.BooleanField(default=False, verbose_name='به کالیپر افزوده شد'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='save_only',
            field=models.BooleanField(default=False, verbose_name='صرفا جهت ذخیره سازی در دیتابیس'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='subscapular_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر تحت کتفی'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='suprailiac_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر سه\u200cتیغ خاصره'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='thigh_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر جلوی ران'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='triceps_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کالیپر پشت بازو'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='workout_types',
            field=models.JSONField(blank=True, default=list, verbose_name='انواع برنامه تمرینی'),
        ),
    ]
