# Generated by Django 4.2.15 on 2026-09-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_coachrequest_abdominal_mm_coachrequest_axilla_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='pushed_health_to_records',
            field=models.BooleanField(default=False, verbose_name='اطلاعات سلامت به سوابق افزوده شد'),
        ),
    ]
