# Generated by Django 4.2.15 on 2026-09-29 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_coachrequest_pushed_health_to_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='training_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='سابقه تمرین (سال)'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='training_sports',
            field=models.TextField(blank=True, verbose_name='ورزش\u200cهای انجام\u200cشده'),
        ),
    ]
