# Generated by Django 4.2.15 on 2026-10-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_seed_prescriptions_for_goal_catalog_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام حرکت')),
                ('name_en', models.CharField(blank=True, max_length=160, verbose_name='نام انگلیسی حرکت')),
                ('performance_type', models.CharField(choices=[('interval', 'اینتروال'), ('continuous', 'تداومی')], max_length=20, verbose_name='نوع انجام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cardio_exercises/', verbose_name='تصویر حرکت')),
            ],
            options={
                'verbose_name': 'حرکت هوازی',
                'verbose_name_plural': 'کتابخانه تمرینات هوازی',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='workoutprogramexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_items', to='account.exercise', verbose_name='حرکت اصلی'),
        ),
        migrations.AddField(
            model_name='workoutprogramexercise',
            name='cardio_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_items', to='account.cardioexercise', verbose_name='حرکت هوازی'),
        ),
        migrations.AddConstraint(
            model_name='workoutprogramexercise',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cardio_exercise__isnull', True), ('exercise__isnull', False)), models.Q(('cardio_exercise__isnull', False), ('exercise__isnull', True)), _connector='OR'), name='workout_program_exercise_one_movement'),
        ),
    ]
