from django.urls import path

from . import gym_views, views

urlpatterns = [
    path("admin/", views.AdminSearchView.as_view(), name="admin_search"),
    path("admin/users/<int:user_id>/", views.AdminUserHubView.as_view(), name="admin_user_hub"),
    path("admin/users/<int:user_id>/personal/", views.AdminPersonalInfoView.as_view(), name="admin_personal_info"),
    path("admin/users/<int:user_id>/health/", views.AdminHealthRecordView.as_view(), name="admin_health"),
    path("admin/users/<int:user_id>/health/<int:pk>/edit/", views.AdminHealthRecordView.as_view(), name="admin_health_edit"),
    path("admin/users/<int:user_id>/health/<int:pk>/delete/", views.AdminHealthRecordDeleteView.as_view(), name="admin_health_delete"),
    path("admin/users/<int:user_id>/circumference/", views.AdminCircumferenceView.as_view(), name="admin_circumference"),
    path("admin/users/<int:user_id>/circumference/<int:pk>/edit/", views.AdminCircumferenceEditView.as_view(), name="admin_circumference_edit"),
    path("admin/users/<int:user_id>/caliper/", views.AdminCaliperView.as_view(), name="admin_caliper"),
    path("admin/users/<int:user_id>/caliper/<int:pk>/edit/", views.AdminCaliperEditView.as_view(), name="admin_caliper_edit"),
    path("admin/users/<int:user_id>/measurements/", views.AdminMeasurementHistoryView.as_view(), name="admin_measurement_history"),
    path("admin/users/<int:user_id>/analysis/", views.AdminUserAnalysisView.as_view(), name="admin_user_analysis"),
    path("admin/users/<int:user_id>/upload/", views.AdminUploadView.as_view(), name="admin_upload"),
    path("admin/users/<int:user_id>/files/", views.AdminUserFilesView.as_view(), name="admin_user_files"),
    path("admin/users/<int:user_id>/files/<str:file_kind>/<int:pk>/delete/", views.AdminUserFileDeleteView.as_view(), name="admin_user_file_delete"),
    path("admin/users/<int:user_id>/role/", views.AdminRoleToggleView.as_view(), name="admin_role_toggle"),
    path("admin/users/<int:user_id>/coach-requests/read/", views.AdminUserCoachRequestsReadView.as_view(), name="admin_user_coach_requests_read"),
    path("admin/coach-requests/<int:pk>/handled/", views.CoachRequestMarkHandledView.as_view(), name="admin_coach_request_handled"),
    path("admin/coach-requests/<int:pk>/push-measurements/", views.CoachRequestPushMeasurementsView.as_view(), name="admin_coach_request_push"),
    path("admin/notifications/", views.AdminNotificationsView.as_view(), name="admin_notifications"),
    path("admin/notifications/moderate/", views.AdminCommentModerationView.as_view(), name="admin_comment_moderate"),
    path("admin/library/", gym_views.GymLibraryView.as_view(), name="admin_gym_library"),
    path("admin/automatic-programming/", gym_views.AutomaticProgrammingView.as_view(), name="admin_automatic_programming"),
    path("admin/users/<int:user_id>/programs/", gym_views.AdminProgramListView.as_view(), name="admin_program_list"),
    path("admin/users/<int:user_id>/programs/add/", gym_views.AdminProgramFormView.as_view(), name="admin_program_add"),
    path("admin/users/<int:user_id>/programs/<int:pk>/edit/", gym_views.AdminProgramFormView.as_view(), name="admin_program_edit"),
    path("admin/users/<int:user_id>/programs/<int:pk>/delete/", gym_views.AdminProgramDeleteView.as_view(), name="admin_program_delete"),
    path("admin/users/<int:user_id>/programs/<int:pk>/pdf/", gym_views.AdminProgramPdfView.as_view(), name="admin_program_pdf"),
    path("admin/library/muscles/", gym_views.MuscleListView.as_view(), name="admin_muscle_list"),
    path("admin/library/muscles/add/", gym_views.MuscleFormView.as_view(), name="admin_muscle_add"),
    path("admin/library/muscles/<int:pk>/edit/", gym_views.MuscleFormView.as_view(), name="admin_muscle_edit"),
    path("admin/library/muscles/<int:pk>/delete/", gym_views.MuscleDeleteView.as_view(), name="admin_muscle_delete"),
    path("admin/library/exercises/", gym_views.ExerciseListView.as_view(), name="admin_exercise_list"),
    path("admin/library/exercises/add/", gym_views.ExerciseFormView.as_view(), name="admin_exercise_add"),
    path("admin/library/exercises/<int:pk>/edit/", gym_views.ExerciseFormView.as_view(), name="admin_exercise_edit"),
    path("admin/library/exercises/<int:pk>/delete/", gym_views.ExerciseDeleteView.as_view(), name="admin_exercise_delete"),
    path("admin/library/correctives/", gym_views.CorrectiveExerciseListView.as_view(), name="admin_corrective_list"),
    path("admin/library/correctives/add/", gym_views.CorrectiveExerciseFormView.as_view(), name="admin_corrective_add"),
    path("admin/library/correctives/<int:pk>/edit/", gym_views.CorrectiveExerciseFormView.as_view(), name="admin_corrective_edit"),
    path("admin/library/correctives/<int:pk>/delete/", gym_views.CorrectiveExerciseDeleteView.as_view(), name="admin_corrective_delete"),
    path("admin/library/lookup/<slug:key>/", gym_views.LookupListView.as_view(), name="admin_lookup_list"),
    path("admin/library/lookup/<slug:key>/add/", gym_views.LookupFormView.as_view(), name="admin_lookup_add"),
    path("admin/library/lookup/<slug:key>/<int:pk>/edit/", gym_views.LookupFormView.as_view(), name="admin_lookup_edit"),
    path("admin/library/lookup/<slug:key>/<int:pk>/delete/", gym_views.LookupDeleteView.as_view(), name="admin_lookup_delete"),
    path("admin/coaches/", views.AdminCoachManagementView.as_view(), name="admin_coach_management"),
    path("admin/password-change/", views.AdminPasswordChangeView.as_view(), name="admin_password_change"),
    path("admin/clients/", views.AdminUserListView.as_view(), name="admin_user_list"),
    path("admin/clients/add/", views.AdminUserCreateView.as_view(), name="admin_user_add"),
    path("admin/clients/<int:user_id>/delete/", views.AdminUserDeleteView.as_view(), name="admin_user_delete"),
]
